version: "3"

services:
  frontend:
    image: frontend:latest
    ports:
      - 5173:5173
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      SPRING_DB_URL: postgresql://db:5432/java
    ports:
      - 8080:8080

  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_DB: java
      POSTGRES_HOST_AUTH_METHOD: trust