version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: java-labs-front
    ports:
      - "5174:5173"
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      SPRING_DB_URL: postgresql://db:5432/java
    ports:
      - "8080:8080"

  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      POSTGRES_DB: java
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: